# See https://doc.mergify.io

pull_request_rules:
  - name: label core
    actions:
      label:
        add: [ contribution/core ]
    conditions:
      - author~=^(pgollucci|ejsiii)$
      - -label~="contribution/core"
  - name: automatic merge
    actions:
      comment:
        message: Thank you for contributing! Your pull request will be updated from master and then merged automatically (do not update manually, and be sure to [allow changes to be pushed to your fork](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)).
      merge:
        strict: smart
        method: squash
        strict_method: merge
        commit_message: title+body
      delete_head_branch: {}
    conditions:
      - base!=release
      - -title~=(WIP|wip)
      - -label~=(blocked|do-not-merge|no-squash)
      - -merged
      - -closed
      - author!=dependabot[bot]
      - author!=dependabot-preview[bot]
  - name: automatic merge
    actions:
      comment:
        message: Thank you for contributing! Your pull request will be updated from master and then merged automatically without squashing (do not update manually, and be sure to [allow changes to be pushed to your fork](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork)).
      merge:
        strict: smart
        # Merge instead of squash
        method: merge
        strict_method: merge
        commit_message: title+body
      delete_head_branch: {}
    conditions:
      - -title~=(WIP|wip)
      - -label~=(blocked|do-not-merge)
      # Only if no-squash is set
      - label~=no-squash
      - -merged
      - -closed
      - author!=dependabot[bot]
      - author!=dependabot-preview[bot]
  - name: if fails conventional commits
    actions:
      comment:
        message: Title does not follow the guidelines of [Conventional Commits](https://www.conventionalcommits.org). Please adjust title before merge.
    conditions:
      - author!=dependabot[bot]
      - author!=dependabot-preview[bot]
      - status-failure=Semantic Pull Request
      - -merged
      - -closed
  - name: automatic merge of Dependabot PRs
    actions:
      comment:
        message: Thanks Dependabot!
      merge:
        # 'strict: false' disables Mergify keeping the branch up-to-date from master.
        # It's not necessary: Dependabot will do that itself.
        # It's not dangerous: GitHub branch protection settings prevent merging stale branches.
        strict: false
        method: squash
      delete_head_branch: {}
    conditions:
      - -title~=(WIP|wip)
      - -label~=(blocked|do-not-merge)
      - -merged
      - -closed
      - author~=dependabot
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge