red="%{$fg[red]%}"
yellow="%{$fg[yellow]%}"
green="%{$fg[green]%}"
blue="%{$fg[blue]%}"
cyan="%{$fg[cyan]%}"
magenta="%{$fg[magenta]%}"
black="%{$fg[black]%}"
white="%{$fg[white]%}"

norm="%{$reset_color%}"
